### ISSUE TITLE
Prepare for code freeze (Contracts)

### ISSUE THREAD

**Issue by lkngtn** [1Hive/dandelion-org#10]

**Comment by willjgriff** [comment]
I think we should make a `frozen-contracts` branch for each app from `master` so we can easily refer to the frozen code after updating front-end code and documentation. The commit hash this branch is made on will likely be requested by the auditors. From that point onwards we won't modify any of the smart contract code. Of course if something needs to be changed we can work something out.

For reference, I'll post a list here with all the frozen commit hashes.

**Comment by willjgriff** [comment]
#### Frozen Solidity commit hash links
Delay app: https://github.com/1Hive/delay-app/tree/0edebf7b07bd44ad00e3ab61ac5c750d440278be/contracts

Token Request app: https://github.com/1Hive/token-request-app/tree/4d0befbba9fef8b2dc8201d41a330cfe5c0deb46/contracts

Token Balance Oracle: https://github.com/1Hive/token-oracle/tree/a9ae2edf9d7654b5a5b8135f49d081dc229c4d30/contracts

Dandelion Voting app: https://github.com/1Hive/dandelion-voting-app/tree/e5b06df5c6bf3c289ce1abc02b7faa1efb0b65f4/contracts

Redemptions app: https://github.com/1Hive/redemptions-app/tree/3d2e74d11f6d2aa8915f560046b5f5658fb63c06/contracts

Token Lock app: https://github.com/1Hive/time-lock-app/tree/57d4d5eaef9f4ade3218527e8942bf17d588bcc3/contracts

Dandelion Template: https://github.com/1Hive/dandelion-org/tree/003e66d29ed40cceb2632655202f17ea1c0a2bb6
