### ISSUE TITLE
Voting, Dissent, Delay interactions

### ISSUE THREAD

**Issue by lkngtn** [1Hive/dandelion-org#19]
A key aspect of the dandelion (and moloch) design is that we can guarantee that if someone votes yes on a proposal they are locked into the org (cannot exit) until that proposal is executed. 

Our initial assumption was to use time to provide this guarantee. We would keep track of when a user votes yes on a proposal and restrict exit for some duration such that we have a reasonable expectation that the vote will be processed before they are able to exit again. 

This works for the most part but there are a few edge cases that can come up that makes it both a bit more complex to explain and a bit fuzzy in terms of actual guarantees. 

In the current design, we set the following related parameters in the Voting, Delay, and Dissent Oracle:

1) Vote buffer (determines how much time in blocks must pass between the start of each vote)
2) Vote duration (determines how long from the start of a vote till it ends, and can then be executed if its passed)
3) Delay duration (determines how long in block time from when an intent is passed to the delay app before it can be executed)
4) Dissent duration (determines number of blocks must have passed between when a user most recently voted yes on a proposal before they can perform an action such as redeem)

Their are two issues with this approach which we have discovered and need to determine how to resolve:

1. We cannot account for the time it takes for a transaction which executes a vote, or executes a delayed action to occur. This requires user action and could vary significantly. 
2. We are mixing blocks and block time when using between the voting app, delay app, and dissent oracle. Meaning the setting and properties must be estimated since there is not necessarily a permanent or fully accurate translation between block time and block number. 

### Convert Delay app to block number

We could convert the delay app to use block number instead of block time, this poses a ux challenge because the radspec description would show the delay in terms of block number which is not really intuitive for users. 

It would also not address the first issue, only the second. 

### Convert dissent oracle and voting to use block time

We could convert the voting app and dissent oracle to use block time instead of block number. The main challenge and reason we didn't do this originally is that since proposals are queued we do not necessarily know which block number to use for the vote snapshot (since we are not necessarily processing the transaction right when the vote starts). 

It might be reasonable to take the snapshot at the time the first vote is cast, but this may be a bit confusing. 

This also would only address the first issue

### Remove the Delay app and add Delay period to the voting app, ensure proposals are executed in sequence. 

This would solve both the first and the second issue and is probably the cleanest solution. The Delay app may still be useful outside of the dandelion org template, so we should still publish it, but it wouldn't be used in the dandelion org template. 

By combining the delay and voting app into a single app we can also simplify and improve how we handle dissent. Rather than keeping track of dissent based on time, we can use proposal number like in moloch, so when a user votes yes we on a proposal we keep track of the "highest" proposal index they have voted yes in. 

We then ensure that proposals must be processed/executed in sequence, lowest to highest. The dissent oracle can evaluate if the current proposal index (yet to be processed) > the users highest index value they voted yes on.

**Comment by lkngtn** [comment]
My instinct is to go with the approach of removing the delay app, adding a delay period to the voting app, and adjusting the dissent oracle logic such that it is based on proposal indexes rather than blocks/time.

**Comment by fabriziovigevani** [comment]
I lean towards the same approach. Seems the least cumbersome and simplest

Contract side we would have to add 

-  `canPerform` oracle function

- additional delay period (should it be able to be changed?)

- replace `lastYeaVoteBlock` for index that tracks the last executed vote id

- Change logic for when a vote can be executed

## Update:

- Change `canVote` logic to reflect  #20

**Comment by lkngtn** [comment]
> additional delay period (should it be able to be changed?)

I think its reasonable for this to be changeable

> index that tracks the last executed vote 

We can probably replace the current time snapshot and data structure since it wount be used any longer. 

> Change logic for when a vote can be executed

is this related to this issue specifically or #20 ? 

A few other changes this would impact, on the frontend we wouldn't need the last time yes voted, this would simply be implicit based on vote cards. 

We would need to update the onboarding and template a bit (to remove delay, and add the delay param to the voting screen, and remove the dissent oracle from the template if we include that check in the voting app itself, update the permissions appropriately).

**Comment by fabriziovigevani** [comment]
> We can probably replace the current time snapshot and data structure since it wount be used any longer.

Yep, list updated

> is this related to this issue specifically or #20 ?

Related to this issue specifically, we would also have to add the logic for `canVote` function to reflect #20 (will update the list)

**Comment by willjgriff** [comment]
The third solution seems a good idea to me. TBH I overlooked that the purpose of the delay app was to delay executing votes (eg I didn't put a permission on the `executeVote()` function in the Dandelion Voting app function, oops...).

> The dissent oracle can evaluate if the current proposal index (yet to be processed) > the users highest index value they voted yes on.

Are you suggesting we no longer use the time of the last vote a user voted in favour of and instead just whether they have voted in favour of the most recent proposal? And if so, should they be able to call `redeem()` as soon as the proposal has been executed? And does it matter if the `voteBuffer` is very small, eg a user could vote yes on many votes, but then create a vote on which they don't vote so they can call `redeem()`?

> We then ensure that proposals must be processed/executed in sequence, lowest to highest.

This can be added as it is.

**Comment by lkngtn** [comment]
> The third solution seems a good idea to me. TBH I overlooked that the purpose of the delay app was to delay executing votes (eg I didn't put a permission on the executeVote() function in the Dandelion Voting app function, oops...). 

I think that's actually okay (though if we go with the suggested approach and remove delay its not actually so relevant anymore 😅), its fine if that is open because the votes would only ever be passing to the delay app. (since all permissions for doing anything are granted to the delay app and not the voting app directly). 

> Are you suggesting we no longer use the time of the last vote a user voted in favour of and instead just whether they have voted in favour of the most recent proposal? And if so, should they be able to call redeem() as soon as the proposal has been executed? And does it matter if the voteBuffer is very small, eg a user could vote yes on many votes, but then create a vote on which they don't vote so they can call redeem()?

Correct, the dissent oracle would not consider time at all and instead operate under the assumption that proposals are "processed" in order and that we keep track of the highest index number an individual has voted yes on. 

When a user votes yes we check if the proposal they are voting on has a higher index number than what is currently stored for them. (Bob votes yes on proposal # 2, we update the value for bob to 2, he then votes yes on proposal # 1, we leave the value as 2, he then votes yes on proposal # 3, we update the value to 3). 

In the dissent oracle, we simply check the value for the user and validate that that proposal has either been executed or failed to pass. (Bob tries to redeem, the dissent oracle see the the index value of the vote Bob last voted yes in is 3, it checks the status of vote # 3 and if it has already be executed, or if it failed then the dissent oracle returns true for canPerform). 

This process is much closer to how Moloch DAO proposals/ragequit work which will make comparisons much simpler. It may be useful to cross reference the castvote and ragequit flows here: https://github.com/MolochVentures/moloch 

> This can be added as it is.

Cool, how exactly?

**Comment by willjgriff** [comment]
> > This can be added as it is.
> 
> Cool, how exactly?

Because we already store the vote ID's, which are created in the sequence of vote creation, so we can easily ensure proposals are executed in order.

To clarify the Dandelion Voting app should now:
- Implement the ACLOracle contract, using the latest voteId instead of time to determine if the user can perform a function.
- Include a modifiable delay period which specifies the delay between when a vote finishes and when it can be executed.
- Ensure votes are executed in order of creation.
- Use the lowest of 'snapshot vote token balance' and 'current vote token balance' as a voters vote weight.

I'll start working on the above but tell me if there's anything else. Note that we will still use blocks to determine vote length, vote buffer (minimum period between votes) and now execution delay.

**Comment by lkngtn** [comment]
@willjgriff This sounds accurate to me. 

One possible nuance, if a vote is rejected, it should be possible for someone who voted yes on that to exit after the vote has been rejected but before the delay period has elapsed. I think this would only impact the logic in the ACLOracle canPerform function.
