### ISSUE TITLE
Redemptions and Snapshot Based Voting

### ISSUE THREAD

**Issue by lkngtn** [1Hive/dandelion-org#20]
There is currently an issue with the dandelion org template that allows someone to get away with voting yes and exiting before a proposal is executed. 

The user can wait for a vote to be created (and the balance snapshot taken), then redeem before voting yes, then voting (they will have voting weight because the balance snapshot is in the past). 

To resolve this we need to add a check to cast vote, which prevents a user from voting if their current balance is less than the snapshot balance. 

Ideally we would allow them to cast a vote for their current balance in this case (though not sure if this is feasible).

**Comment by fabriziovigevani** [comment]
Under the assumption that the tokens are non-transferable i think we can directly check for the current balance  cc @willjgriff

**Comment by lkngtn** [comment]
I think that would be safe for transferable tokens as well, given that it would always give you the lesser of the two values.

**Comment by willjgriff** [comment]
We can use the lesser of the two values (voter snapshot balance, voter current balance) to determine their vote weight, I don't see a problem with that.

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/dandelion-voting-app/pull/22

**Comment by fabriziovigevani** [comment]
closed by 1Hive/dandelion-voting-app#22
