### ISSUE TITLE
Onboarding field validation

### ISSUE THREAD

**Issue by lkngtn** [1Hive/dandelion-org#21]
Remove validation on fields:
- Vote Duration
- Vote Buffer
- Delay Duration
- Lock Duration 

It should be possible (even for testing/demo purposes) to specificy lower amounts. Also currently the error message is specific to vote duration, but is being applied on fields other than vote duration.

**Comment by rperez89** [comment]
closed by commit [aragon 1hiveOnboarding branch](https://github.com/1Hive/aragon/commit/704863ae1df7b8128776fa95da4607c54c9c7794)
