### ISSUE TITLE
Update link in Dandelion Template Preview

### ISSUE THREAD

**Issue by lkngtn** [1Hive/dandelion-org#45]
![image](https://user-images.githubusercontent.com/4986634/74182997-1265b880-4c12-11ea-9f74-300754f2ea88.png)

Lets update this to say:

**Documentation**
http://dandelion.1hive.org

**Comment by fabriziovigevani** [comment]
closed by https://github.com/aragon/aragon/pull/1271/commits/837bed8bb988d8e4c8fde6ec152d6d6a79434385
