### ISSUE TITLE
Is it possible to add tokens via Token or only via Token Request?

### ISSUE THREAD

**Issue by marsrobertson** [1Hive/dandelion-org#49]
My token request #48 is failing so I thought about generating tokens the old way.

### BUT

![image](https://user-images.githubusercontent.com/44369284/76397198-8fe82a00-6372-11ea-8ca7-fa7ebea87a99.png)

Therefore fails:
![aragon tokens add dandellion](https://user-images.githubusercontent.com/44369284/76397258-adb58f00-6372-11ea-9073-ac3702e94c3a.gif)

(not sure if MetaMask errors in the console are related)

**Comment by lkngtn** [comment]
By default the only way to mint tokens is through token request, however, the voting app is the the permission manager so you can create a vote to assign that permission to either the voting app or even your own account. 

It may make sense for us to consider having the mint/burn permissions also assigned to the voting app by default in a future version of the template.

**Comment by marsrobertson** [comment]
Thank you for explaining.

Now I understand I can assign token permission to the voting app.
